from fastapi import APIRouter, UploadFile, File, Form, HTTPException, BackgroundTasks
from app.services.ai_interviewer import transcribe_audio, evaluate_answer
from app.core.db import get_database
import datetime
import uuid

router = APIRouter()

# Simple MVP static questions. In a full product, these would be generated by LLM based on job description.
ROLE_QUESTIONS = {
    "default": [
        {"id": "q1", "text": "Can you briefly introduce yourself and highlight your relevant experience?"},
        {"id": "q2", "text": "What is the most challenging technical problem you have solved recently, and how did you approach it?"},
        {"id": "q3", "text": "How do you ensure the quality and maintainability of your code?"}
    ]
}

@router.get("/{interview_id}/questions")
async def get_questions(interview_id: str, role: str = "default"):
    """
    Returns the list of questions for the AI interview.
    """
    questions = ROLE_QUESTIONS.get(role, ROLE_QUESTIONS["default"])
    return {"success": True, "questions": questions}

@router.post("/{interview_id}/audio")
async def process_audio(
    interview_id: str,
    question_id: str = Form(...),
    question_text: str = Form(...),
    job_title: str = Form("Software Engineer"),
    audio: UploadFile = File(...)
):
    """
    Receives an audio file, transcribes it via Whisper, evaluates via Llama3, and saves the result to MongoDB.
    """
    if not audio.filename.endswith((".webm", ".wav", ".mp3", ".mp4")):
        raise HTTPException(status_code=400, detail="Unsupported audio format. Use webm, wav, or mp3.")

    try:
        # Read the audio bytes
        audio_bytes = await audio.read()
        
        # 1. Transcribe Audio
        transcript = await transcribe_audio(audio_bytes)
        
        # 2. Evaluate Answer
        evaluation = evaluate_answer(
            question=question_text,
            answer=transcript,
            job_title=job_title
        )
        
        # 3. Store Result in DB
        db = get_database()
        if db is not None:
            try:
                # We store each answer as a document or push to an array. Let's just push to a single document for the interview.
                await db["ai_interviews"].update_one(
                    {"interview_id": interview_id},
                    {
                        "$setOnInsert": {
                            "interview_id": interview_id,
                            "job_title": job_title,
                            "created_at": datetime.datetime.utcnow(),
                        },
                        "$push": {
                            "responses": {
                                "response_id": str(uuid.uuid4()),
                                "question_id": question_id,
                                "question_text": question_text,
                                "transcript": transcript,
                                "score": evaluation.get("score"),
                                "feedback": evaluation.get("feedback"),
                                "is_complete": evaluation.get("is_complete"),
                                "timestamp": datetime.datetime.utcnow()
                            }
                        }
                    },
                    upsert=True
                )
            except Exception as db_err:
                print(f"Warning: Failed to save to MongoDB: {db_err}")
        
        return {
            "success": True,
            "transcript": transcript,
            "evaluation": evaluation
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing audio: {str(e)}")

@router.post("/{interview_id}/complete")
async def complete_interview(interview_id: str):
    """
    Marks the interview as completed and computes the final aggregate score.
    """
    try:
        db = get_database()
        if db is None:
            return {"success": False, "message": "No database connection"}
            
        record = await db["ai_interviews"].find_one({"interview_id": interview_id})
        if not record or not record.get("responses"):
            return {"success": False, "message": "No responses found"}
            
        responses = record["responses"]
        total_score = sum(r.get("score", 0) for r in responses)
        avg_score = total_score / len(responses) if responses else 0
        
        try:
            # Update record with final status and score
            await db["ai_interviews"].update_one(
                {"interview_id": interview_id},
                {"$set": {
                    "status": "COMPLETED",
                    "final_score": avg_score,
                    "completed_at": datetime.datetime.utcnow()
                }}
            )
        except Exception as db_err:
            print(f"Warning: Failed to update MongoDB: {db_err}")
        
        # Note: In a full implementation, we could emit a webhook or use Socket.io to notify the Node.js ATS backend here.
        
        return {
            "success": True,
            "final_score": avg_score
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
