export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HR_RECRUITER: 'HR_RECRUITER',
  SENIOR_MANAGER: 'SENIOR_MANAGER',
  EMPLOYEE: 'EMPLOYEE'
};

export const PERMISSIONS = {
  VIEW_ATS: 'VIEW_ATS',
  MANAGE_CANDIDATES: 'MANAGE_CANDIDATES',
  SCHEDULE_INTERVIEWS: 'SCHEDULE_INTERVIEWS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_ONBOARDING: 'MANAGE_ONBOARDING',
  VIEW_EMPLOYEE_PORTAL: 'VIEW_EMPLOYEE_PORTAL',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',
  VIEW_APPROVALS: 'VIEW_APPROVALS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  
  // Senior Manager Permissions
  VIEW_TEAM_DASHBOARD: 'VIEW_TEAM_DASHBOARD',
  APPROVE_LEAVES: 'APPROVE_LEAVES',
  ASSIGN_TASKS: 'ASSIGN_TASKS',
  CONDUCT_INTERVIEWS: 'CONDUCT_INTERVIEWS',
  VIEW_TEAM_ANALYTICS: 'VIEW_TEAM_ANALYTICS'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // Admin has all permissions
  
  [ROLES.HR_RECRUITER]: [
    PERMISSIONS.VIEW_ATS,
    PERMISSIONS.MANAGE_CANDIDATES,
    PERMISSIONS.SCHEDULE_INTERVIEWS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_ONBOARDING
  ],
  
  [ROLES.SENIOR_MANAGER]: [
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_APPROVALS,
    PERMISSIONS.SCHEDULE_INTERVIEWS,
    PERMISSIONS.VIEW_EMPLOYEE_PORTAL,
    PERMISSIONS.VIEW_TEAM_DASHBOARD,
    PERMISSIONS.APPROVE_LEAVES,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CONDUCT_INTERVIEWS,
    PERMISSIONS.VIEW_TEAM_ANALYTICS
  ],
  
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_EMPLOYEE_PORTAL
  ]
};

export const hasPermission = (userRole, permission) => {
  const rolePerms = ROLE_PERMISSIONS[userRole];
  return rolePerms ? rolePerms.includes(permission) : false;
};
